version: '3'
services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent_test
    container_name: agent
    volumes:
      - ./logs:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/systemd/journal/socket:/run/systemd/journal/socket
      - /dev/log:/dev/log
    privileged: true
    network_mode: host
    environment:
      - PULL_SECRET_TOKEN=OpenShiftToken
      - WIREMOCK_PORT
    command: ["/usr/bin/agent","--url","http://127.0.0.1:${WIREMOCK_PORT}", "--cluster-id", "11111111-1111-1111-1111-111111111111", "--interval", "5"]

  dhcpd:
    image: networkboot/dhcpd
    container_name: dhcpd
    cap_add:
      - net_raw
    volumes:
      - ${ROOT_DIR}/subsystem/data:/data
    network_mode: host
    environment:
      - ROOT_DIR
    command: eth0

  wiremock:
    image: "rodolpheche/wiremock"
    ports:
      - "${WIREMOCK_PORT}:${WIREMOCK_PORT}"
    network_mode: host
    environment: 
      - WIREMOCK_PORT
    volumes:
      - ./wiremock:/home/wiremock
    command: --port ${WIREMOCK_PORT}